tatami-dev-cassandra:
  container_name: tatami-dev-cassandra
  build: .
  dockerfile: cassandra/Cassandra-Dev.Dockerfile
  # volumes:
  #   - ~/volumes/jhipster/tatami/dev-cassandra/:/var/lib/cassandra/data
  ports:
    - "7000:7000"
    - "7001:7001"
    - "7199:7199"
    - "9042:9042"
    - "9160:9160"
